// Theme extracted from Figma design, adapted for React Native
const theme = {
  colors: {
    primary: '#6750A4',
    onPrimary: '#FFFFFF',
    primaryContainer: '#EADDFF',
    onPrimaryContainer: '#21005D',
    secondary: '#625B71',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#E8DEF8',
    onSecondaryContainer: '#1D192B',
    tertiary: '#7D5260',
    onTertiary: '#FFFFFF',
    surface: '#1C1B1F',
    onSurface: '#E6E1E5',
    surfaceVariant: '#49454F',
    onSurfaceVariant: '#CAC4D0',
    background: '#292430',
    onBackground: '#E6E1E5',
    error: '#F2B8B5',
    onError: '#601410',
    outline: '#938F99',
    outlineVariant: '#49454F',
    success: '#4CAF50',
    warning: '#FF9800',
    info: '#2196F3',
    surfaceTint: '#6750A4',
    surfaceContainer: '#211F26',
    surfaceContainerHigh: '#2B2930',
    surfaceContainerHighest: '#36343B',
    surfaceContainerLow: '#1C1B1F',
    surfaceContainerLowest: '#0F0D13',
    surfaceBright: '#3B383E',
    surfaceDim: '#141218',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    xxl: 20,
    round: 999,
    modal: 16,
    card: 14,
    topSheet: 18,
  },
  fonts: {
    regular: 'Poppins-Regular',
    bold: 'Poppins-Bold',
    semiBold: 'Poppins-SemiBold',
    extraBold: 'Poppins-ExtraBold',
  },
  fontWeights: {
    regular: '400',
    medium: '500',
    semiBold: '600',
    bold: '700',
    extraBold: '900',
  },
  swipe: {
    yesBg: 'rgba(34,197,94,0.18)', // brighter green, lower opacity
    yesOverlay: 'rgba(34,197,94,0.38)', // brighter green, higher opacity
    yesText: '#22c55e',
    noBg: 'rgba(239,68,68,0.18)', // brighter red, lower opacity
    noOverlay: 'rgba(239,68,68,0.38)', // brighter red, higher opacity
    noText: '#ef4444',
  },
  overlay: {
    modal: 'rgba(0,0,0,0.5)',
    fullScreen: 'rgba(0,0,0,0.82)',
    status: 'rgba(0,0,0,0.7)',
  },
  elevation: {
    level0: {
      shadowColor: 'transparent',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    level1: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 1,
    },
    level2: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 2,
    },
    level3: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 3,
    },
    level4: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.35,
      shadowRadius: 16,
      elevation: 4,
    },
    level5: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 20,
      elevation: 5,
    },
  },
};

export default theme; 